services:
  resource-db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${RESOURCE_DB_NAME}
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d

  song-db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${SONG_DB_NAME}
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  resource-service:
    build: ./resource-service
    ports:
      - "8071:8071"
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_PASSWORD}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      EUREKA_INSTANCE_HOSTNAME: resource-service
    depends_on:
      - resource-db
      - eureka-server

  song-service:
    build: ./song-service
    ports:
      - "8072"
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_PASSWORD}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      EUREKA_INSTANCE_HOSTNAME: song-service
    depends_on:
      - song-db
      - eureka-server
