server:
  port: 8081

spring:
  application:
    name: song-service
  datasource:
    url: jdbc:postgresql://localhost:5433/song_db
    username: song_user
    password: song_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false