server:
  port: "${EUREKA_PORT:8761}"

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: "${EUREKA_HOSTNAME:localhost}"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8761}/eureka/"
