server:
  port: 8080

spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://localhost:5432/resource_db
    username: resource_user
    password: resource_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

song-service:
  base-url: http://localhost:8081
